"""empty message

Revision ID: 211b510d641f
Revises: a459e824350b
Create Date: 2021-07-31 00:55:34.429271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211b510d641f'
down_revision = 'a459e824350b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_hardiness_zone_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_hardiness_zone_key', 'user', ['hardiness_zone'])
    # ### end Alembic commands ###
