"""empty message

Revision ID: 3a4345e1f263
Revises: f012c38a0e76
Create Date: 2021-07-24 00:03:19.694541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4345e1f263'
down_revision = 'f012c38a0e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('plant_username_fkey', 'plant', type_='foreignkey')
    op.create_foreign_key(None, 'plant', 'user', ['user_id'], ['id'])
    op.drop_column('plant', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('username', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plant', type_='foreignkey')
    op.create_foreign_key('plant_username_fkey', 'plant', 'user', ['username'], ['id'])
    op.drop_column('plant', 'user_id')
    # ### end Alembic commands ###
