"""empty message

Revision ID: 960643d44232
Revises: 211b510d641f
Create Date: 2021-07-31 11:19:51.028418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960643d44232'
down_revision = '211b510d641f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('experience', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'experience')
    # ### end Alembic commands ###
