"""empty message

Revision ID: a459e824350b
Revises: 2edab2e5b2d6
Create Date: 2021-07-29 08:32:08.523137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a459e824350b'
down_revision = '2edab2e5b2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hardiness_zone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('zipcode', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['hardiness_zone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'zipcode')
    op.drop_column('user', 'hardiness_zone')
    # ### end Alembic commands ###
